# Generated by Django 2.2.4 on 2019-09-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190906_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
    ]
