# Generated by Django 2.2.4 on 2019-09-03 03:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='portfolio/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('client', models.CharField(max_length=45)),
                ('website', models.URLField(blank=True, null=True)),
                ('complete_date', models.DateField()),
                ('is_draft', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
